### ISSUE TITLE
Pages not rendering with CSS?

### ISSUE THREAD

**Issue by joewheaton** [Restoration-USU/WATS-5340-5350#1]
Hey Phlip,
I attempted to look at the changes you made to the [pyBRAT repo](https://github.com/Riverscapes/pyBRAT) and your instructions on using the [Jeckyll Toolbox](http://riverscapes.northarrowresearch.com/Technical_Reference/jekyll_toolbox.html) for sites (that I know you haven't finished), and switch this site over (https://github.com/Restoration-USU/WATS-5340-5350/commit/cfd1625dc28748526261e836a21de1bbe0302ee1) based loosely on https://github.com/Riverscapes/pyBRAT/commit/f19ff026c741faf06e759a714505bbb18fe9776f...  Some things are obviously working, but many are not.  The main problems seem to be:
* [ ] Banner not loading
* [ ] Sidebar Navigation not populating automatically for page content or site contents (also not rendering CSS)
* [ ] [SCSS](https://github.com/Restoration-USU/WATS-5340-5350/tree/master/src/scss) not apparently being used. 

What am I screwing up?

**Comment by philipbaileynar** [comment]
@joewheaton what's the URL that this site serves from? You've gone for a site in the root folder instead of docs, which is totally fine. But I think that the hyphens in the repo name are preventing me from deducing the URL for the site. And because I don't have admin privileges for this organization, I can't see the Settings tab on the repo to see how you've configured this site.

**Comment by joewheaton** [comment]
Hey @philipbaileynar. Adderess for now was: https://restoration-usu.github.io/WATS-5340-5350/ and you should have admin access now...

**Comment by philipbaileynar** [comment]
@joewheaton this was fixed by two super minor tweaks:

1. The config was refering to the site URL using https and apparently this needs to be http. Fixed with commit afb9a7c1d7a0a18ee879833de518557fc6c816fb
1. The config specified the site url using both the url and also the base url. Here's [explanatory documentation](https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/). Fixed with commit c60821ae8610e454dd8dc84c767a01c7e5cc5318.

Appears to be working now.

**Comment by joewheaton** [comment]
Thanks @philipbaileynar! Good to know.
